// GENERATED by tools/dump_rider_sprites.py from TPW.BIN. Do not edit by hand.
namespace TPW.Sim
{
    /// <summary>READ 0x800E0140. Which sprite a rider is drawn as, by visitor type, facing and elevation
    /// band -- and a rider is a HEAD, not a body: sitting in a car, the head is all that shows.
    ///
    /// ⚠ THESE ARE SPRITES OF FOLIO ENTRY 416, the common sheet (HUD frames, font, particles), NOT of the
    /// people sheet 269 that walking guests come from. Absolute indices, no per-type base. Looking for
    /// them in 269 finds another guest's walk cycle at the same numbers, which is convincing and wrong.
    /// findings/rider-positions.md §8.</summary>
    public static class RiderSprites
    {
        public const int Types = 8, PerType = 17;

        /// <summary>[type][facing + 8 * band]. Band 2 holds one sprite at index 16 and ignores facing.</summary>
        public static readonly int[][] Table =
        {
            new[] { 116, 117, 118, 119, 120, 119, 118, 117, 111, 112, 113, 114, 115, 114, 113, 112, 110 },
            new[] { 127, 128, 129, 130, 131, 130, 129, 128, 122, 123, 124, 125, 126, 125, 124, 123, 121 },
            new[] { 138, 139, 140, 141, 142, 141, 140, 139, 133, 134, 135, 136, 137, 136, 135, 134, 132 },
            new[] { 149, 150, 151, 152, 153, 152, 151, 150, 144, 145, 146, 147, 148, 147, 146, 145, 143 },
            new[] {  72,  73,  74,  75,  76,  75,  74,  73,  67,  68,  69,  70,  71,  70,  69,  68,  66 },
            new[] {  83,  84,  85,  86,  87,  86,  85,  84,  78,  79,  80,  81,  82,  81,  80,  79,  77 },
            new[] {  94,  95,  96,  97,  98,  97,  96,  95,  89,  90,  91,  92,  93,  92,  91,  90,  88 },
            new[] { 105, 106, 107, 108, 109, 108, 107, 106, 100, 101, 102, 103, 104, 103, 102, 101,  99 },
        };

        /// <summary>⭐ THE DEVELOPERS' FACES (0x800F1EEC, DUMPED: 564, 565, 566, 567, 568, 569 -- six
        /// u32s, in order, and the next word is already the ASCII "INTRO.ST"). Six 26..32 x 38..46
        /// photographs of real people on sheet 416.</summary>
        public static readonly int[] DeveloperHeads = { 564, 565, 566, 567, 568, 569 };

        /// <summary>The override at 0x801029F4 (gp+0x3A0). ⚠ NOTHING ON THE DISC SETS IT -- the word is
        /// zero in the image and a census by gp offset and by absolute store finds no writer, so on real
        /// hardware these faces can never appear. A debug switch that shipped, not an easter egg anyone
        /// could reach. Exposed here as `--park-devheads` because the mechanism is fully READ.</summary>
        public static bool DeveloperHeadsEnabled;

        /// <summary>The sprite for a rider, and whether the quad is mirrored in x.
        /// READ: the mirror test is `4 &lt; facing` on the UNMASKED facing, and band 2 zeroes the facing.</summary>
        public static int For(int type, int facing, int band, out bool mirror)
        {
            band = band < 0 ? 0 : band > 2 ? 2 : band;
            if (band == 2) facing = 0;
            mirror = facing > 4;
            // ⚠ THE OVERRIDE IS TAKEN BEFORE THE TABLE, AND IT IGNORES FACING AND BAND -- one face per
            // visitor type, so a rider keeps the same photograph however he turns. The modulus is the
            // game's own (0x801029F0 = 6), not the table's length by coincidence.
            if (DeveloperHeadsEnabled)
                return DeveloperHeads[((type % DeveloperHeads.Length) + DeveloperHeads.Length)
                                      % DeveloperHeads.Length];
            var row = Table[((type % Types) + Types) % Types];
            return band == 2 ? row[16] : row[(facing & 7) + 8 * band];
        }
    }
}
