#!/usr/bin/env python3
"""Render STATUS.md from the live board's database.

    ArtifactData list  <collection>  out_dir=<dir>     (systems, bugs, questions, deviations)
    python3 tools/board_to_status.py <dir> > STATUS.md

⭐ STATUS.md IS GENERATED, NOT MAINTAINED. Master's objection to the old one was exactly right: a
hand-kept file goes stale because it needs someone to remember, which is what happened to the README.
A file with no state of its own cannot disagree with the board -- only be older than it, and it stamps
how old it is at the top so a reader can see that for themselves.

So: the board is the truth, this is a rendering of it, and nobody edits this file by hand. If you are
about to, edit the board instead.
"""
import json, os, sys, datetime

STATE = {"proved": ("PROVED", "measured, with evidence"),
         "built":  ("built",  "runs; nothing has tested it end to end"),
         "work":   ("in progress", ""),
         "none":   ("not started", "")}
GROUPS = ["Assets & world", "Building", "Guests & rides", "Money & progression", "Shell"]


def load(root, coll):
    d = os.path.join(root, coll)
    if not os.path.isdir(d):
        return []
    out = []
    for f in sorted(os.listdir(d)):
        if f.endswith(".json"):
            with open(os.path.join(d, f), encoding="utf-8") as fh:
                out.append(json.load(fh))
    return sorted(out, key=lambda r: (r.get("order") or 0))


def age(iso):
    if not iso:
        return ""
    try:
        t = datetime.datetime.fromisoformat(iso.replace("Z", "+00:00"))
    except ValueError:
        return ""
    days = (datetime.datetime.now(datetime.timezone.utc) - t).days
    if days <= 0:
        return "today"
    return f"{days}d ago" + (" ⚠" if days >= 14 else "")


def main():
    root = sys.argv[1]
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    p = print
    p("# Where the port is")
    p()
    p("⭐ **GENERATED FROM THE LIVE BOARD — DO NOT EDIT THIS FILE.** Edit the board; it saves itself.")
    p("Board: https://claude.ai/artifact/RoeedNAubVjynBFaM2wacn")
    p()
    p(f"Rendered {now}. Everything below is as old as that stamp — the board is never older.")
    p()
    p("**PROVED** means someone measured it. **built** means it runs and nobody has checked. That")
    p("distinction is the load-bearing one: this port's worst bugs were things that compiled fine and")
    p("did nothing.")
    systems = load(root, "systems")
    for g in GROUPS:
        rows = [r for r in systems if r.get("group") == g]
        if not rows:
            continue
        p()
        p(f"## {g}")
        p()
        p("| state | system | owner | last moved | note |")
        p("| --- | --- | --- | --- | --- |")
        for r in rows:
            label = STATE.get(r.get("state"), ("?", ""))[0]
            p(f"| {label} | {r.get('name','')} | {r.get('owner','')} | {age(r.get('updatedAt'))} "
              f"| {r.get('note','')} |")
    for coll, head, cols in (("bugs", "Known bugs", "state"),
                             ("questions", "Open questions — need a human, not more disassembly", None),
                             ("deviations", "Deliberate deviations from the original", None)):
        rows = load(root, coll)
        if not rows:
            continue
        p()
        p(f"## {head}")
        p()
        if cols:
            p("| state | what | owner | note |")
            p("| --- | --- | --- | --- |")
            for r in rows:
                p(f"| {'fixed' if r.get('state') == 'shut' else 'OPEN'} | {r.get('name','')} "
                  f"| {r.get('owner','')} | {r.get('note','')} |")
        else:
            p("| what | owner | note |")
            p("| --- | --- | --- |")
            for r in rows:
                p(f"| {r.get('name','')} | {r.get('owner','')} | {r.get('note','')} |")


if __name__ == "__main__":
    main()
