#!/usr/bin/env python3
"""Dump the rider sprite table (0x800E0140) out of TPW.BIN.

READ 0x80035050 / findings/rider-positions.md §8: a rider is drawn as a HEAD from FOLIO sheet 416,
picked by `0x800E0140[17*type + facing + 8*band]`. The indices are absolute sprite numbers in that
sheet -- no per-type or per-world base. Eight visitor types, 17 entries each:

    0..7   band 0, level      s+6 s+7 s+8 s+9 s+10 s+9 s+8 s+7   (facings 5..7 mirror 3..1)
    8..15  band 1, from above s+1 s+2 s+3 s+4 s+5  s+4 s+3 s+2
    16     band 2, the crown  s                                  (facing forced to 0)

Writes core/TPW.Sim/RiderSprites.cs.
"""
import struct, sys, pathlib

BASE, TABLE, TYPES, PER = 0x80010000, 0x800E0140, 8, 17

def main(binpath, root):
    b = pathlib.Path(binpath).read_bytes()
    rows = []
    for t in range(TYPES):
        row = [struct.unpack_from('<h', b, TABLE - BASE + 2 * (PER * t + i))[0] for i in range(PER)]
        if min(row) < 0:
            sys.exit(f'row {t} has a negative sprite id: {row}')
        rows.append(row)
    body = ',\n'.join('            { ' + ', '.join('%3d' % v for v in r) + ' }' for r in rows)
    (pathlib.Path(root) / 'core/TPW.Sim/RiderSprites.cs').write_text('''// GENERATED by tools/dump_rider_sprites.py from TPW.BIN. Do not edit by hand.
namespace TPW.Sim
{
    /// <summary>READ 0x800E0140. Which sprite a rider is drawn as, by visitor type, facing and elevation
    /// band -- and a rider is a HEAD, not a body: sitting in a car, the head is all that shows.
    ///
    /// ⚠ THESE ARE SPRITES OF FOLIO ENTRY 416, the common sheet (HUD frames, font, particles), NOT of the
    /// people sheet 269 that walking guests come from. Absolute indices, no per-type base. Looking for
    /// them in 269 finds another guest's walk cycle at the same numbers, which is convincing and wrong.
    /// findings/rider-positions.md §8.</summary>
    public static class RiderSprites
    {
        public const int Types = ''' + str(TYPES) + ''', PerType = ''' + str(PER) + ''';

        /// <summary>[type][facing + 8 * band]. Band 2 holds one sprite at index 16 and ignores facing.</summary>
        public static readonly int[][] Table =
        {
''' + body + ''',
        };

        /// <summary>The sprite for a rider, and whether the quad is mirrored in x.
        /// READ: the mirror test is `4 &lt; facing` on the UNMASKED facing, and band 2 zeroes the facing.</summary>
        public static int For(int type, int facing, int band, out bool mirror)
        {
            band = band < 0 ? 0 : band > 2 ? 2 : band;
            if (band == 2) facing = 0;
            mirror = facing > 4;
            var row = Table[((type % Types) + Types) % Types];
            return band == 2 ? row[16] : row[(facing & 7) + 8 * band];
        }
    }
}
''')
    print('%d types x %d entries; sprites %d..%d'
          % (TYPES, PER, min(min(r) for r in rows), max(max(r) for r in rows)))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else '.')
