#!/usr/bin/env python3
"""Dump the advisor's message table (0x800EE4FC, 289 records of 20 bytes) out of TPW.BIN.

READ 0x80013EFC (show) and 0x80013298 (idle state) for the layout:

    +0  u16 textId        string id in FOLIO 0x197; 0x124 is the explicit NO-TEXT sentinel
    +2  u8  count         recorded takes the game will rotate through, 1..3
    +3  u8  cursor        which take is next -- LIVE, the game writes it back into the record
    +4  { u16 line, u16 mood } x 4     takes; `line` indexes ADVISOR.TPW, `mood` is latched
                                       into advisor+0x184 when he starts speaking

The table's length is not stored anywhere. 289 is established two ways that do not share a
method: record 289 is structurally garbage (count 75), and 0x80013C1C's interrupt test is
`(id - 221) < 68`, i.e. ids 221..288 -- exactly the last record. Both give the same last index.

Writes findings/advisor-messages.json and core/TPW.Sim/AdvisorMessages.cs.
"""
import json, struct, sys, pathlib

BASE, TABLE, COUNT, STRIDE = 0x80010000, 0x800EE4FC, 289, 20
NO_TEXT = 0x124

def main(binpath, root):
    b = pathlib.Path(binpath).read_bytes()
    root = pathlib.Path(root)
    texts = json.loads((root / 'findings/statistics-rules.json').read_text())['messages']

    recs = []
    for n in range(COUNT):
        o = TABLE + STRIDE * n - BASE
        tid, cnt, cur = struct.unpack_from('<HBB', b, o)
        takes = [struct.unpack_from('<HH', b, o + 4 + 4 * i) for i in range(4)]
        if cur != 0:
            sys.exit(f'record {n} has a nonzero cursor on disc ({cur}); the image is not a cold table')
        recs.append(dict(id=n, address='0x%08X' % (TABLE + STRIDE * n), text_id=tid, count=cnt,
                         takes=[dict(line=l, mood=m) for l, m in takes[:cnt]],
                         # 22/62/63/77 carry one more take than `count` admits: recorded, then cut.
                         cut_takes=[dict(line=l, mood=m) for l, m in takes[cnt:] if (l, m) != (0, 0)],
                         text=texts.get(str(n), {}).get('text')))

    (root / 'findings/advisor-messages.json').write_text(json.dumps(dict(
        provenance='TPW.BIN SLES-026.88, table 0x800EE4FC, readers 0x80013EFC / 0x80013298 / 0x80014024',
        table_address='0x%08X' % TABLE, record_bytes=STRIDE, record_count=COUNT,
        no_text_id=NO_TEXT, interrupt_first_id=221, interrupt_last_id=COUNT - 1,
        messages=recs), indent=1) + '\n')

    rows = []
    for r in recs:
        t = r['takes'] + [dict(line=0, mood=0)] * (3 - len(r['takes']))
        rows.append('            new(%5d, %d, %s),' % (r['text_id'], r['count'],
                    ', '.join('%3d, %2d' % (x['line'], x['mood']) for x in t[:3])))
    (root / 'core/TPW.Sim/AdvisorMessages.cs').write_text('''// GENERATED by tools/dump_advisor_messages.py from TPW.BIN. Do not edit by hand.
namespace TPW.Sim
{
    /// <summary>One advisor message: a caption and up to three recorded takes of it.</summary>
    /// <param name="TextId">String id in FOLIO 0x197. <see cref="AdvisorMessages.NoText"/> means the
    /// message is deliberately voice-only, not that a caption is missing.</param>
    /// <param name="Count">How many of the three takes the game will actually rotate through.</param>
    public readonly record struct AdvisorMessage(ushort TextId, byte Count,
        ushort Line0, byte Mood0, ushort Line1, byte Mood1, ushort Line2, byte Mood2)
    {
        public ushort Line(int take) => take == 0 ? Line0 : take == 1 ? Line1 : Line2;
        public byte Mood(int take) => take == 0 ? Mood0 : take == 1 ? Mood1 : Mood2;
    }

    /// <summary>READ 0x800EE4FC. The advisor's 289 messages, each with the takes he rotates through so
    /// the same advice is never delivered the same way twice running.</summary>
    public static class AdvisorMessages
    {
        /// <summary>READ 0x80013F48. A caption id of 0x124 means SAY IT WITH NO CAPTION -- the advisor
        /// speaks and no text box opens. It is not a missing string to fill in later.</summary>
        public const ushort NoText = 0x124;

        /// <summary>READ 0x80013C1C. Messages from here up jump the queue and interrupt whatever the
        /// advisor is saying. They are exactly the tail of the table.</summary>
        public const int FirstInterrupt = 221;

        public static readonly AdvisorMessage[] All =
        {
''' + '\n'.join(rows) + '''
        };

        public static bool Has(int id) => id >= 0 && id < All.Length;
    }
}
''')
    print('%d records; %d with no caption; %d carrying a cut take'
          % (len(recs), sum(1 for r in recs if r['text_id'] == NO_TEXT),
             sum(1 for r in recs if r['cut_takes'])))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else '.')
