#!/usr/bin/env python3
"""Decode the advisor's statistic rules, without copying executable/archive bytes.

READ: 0x80016718 loads FOLIO entries 1/2; 0x80017024 interprets signed halfwords.
Usage: python3 tools/statistics.py /path/TPW.BIN /path/FOLIO.GAZ
Writes only in this checkout. See findings/statistics.md for interpretation.
"""
import hashlib
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = 0x80010000
OPS = ('End', 'Equal', 'NotEqual', 'Less', 'Greater', 'Add', 'Set',
       'PostMessage', 'Action8', 'ElapsedGreater')
ARITY = (0, 2, 2, 2, 2, 2, 2, 1, 1, 1)


def decode(binary, archive):
    def entry(index):
        off, size = struct.unpack_from('<II', archive, 8 + 8 * index)
        return off, archive[off:off + size]

    schedule_off, schedule = entry(1)
    code_off, code = entry(2)
    _, strings = entry(0x197)
    words = struct.unpack('<' + 'h' * (len(code) // 2), code)
    rules, messages = [], {}
    for row in range(len(schedule) // 12):
        offset, _, cooldown, _ = struct.unpack_from('<hIHI', schedule, row * 12)
        cursor, instructions = offset, []
        while words[cursor]:
            op = words[cursor]
            if not 1 <= op <= 9:
                raise ValueError(f'unknown instruction {op} in rule {row}')
            args = list(words[cursor + 1:cursor + 1 + ARITY[op]])
            instructions.append(dict(op=OPS[op], args=args, word_offset=cursor))
            if op in (7, 8):
                message = args[0]
                addr = 0x800EE4FC + 20 * message
                text_id = struct.unpack_from('<H', binary, addr - BASE)[0]
                text_off = struct.unpack_from('<I', strings, 4 + 4 * text_id)[0]
                text = strings[text_off:strings.index(b'\0', text_off)].decode('latin1').strip()
                messages[str(message)] = dict(record_address=f'0x{addr:08X}',
                                              text_id=text_id, text=text)
            cursor += 1 + ARITY[op]
        rules.append(dict(index=row, schedule_offset=row * 12, word_offset=offset,
                          cooldown_days=cooldown, instructions=instructions))
    slots = []
    for slot in range(72):
        target = struct.unpack_from('<I', binary, 0x800DB9F8 - BASE + slot * 4)[0]
        readers = [r['index'] for r in rules if any(
            i['op'] in OPS[1:5] and i['args'][0] == slot for i in r['instructions'])]
        writers = [r['index'] for r in rules if any(
            i['op'] in ('Add', 'Set') and i['args'][0] == slot for i in r['instructions'])]
        posts = sorted({i['args'][0] for r in rules if r['index'] in readers
                        for i in r['instructions'] if i['op'] == 'PostMessage'})
        slots.append(dict(index=slot, refresh_case=f'0x{target:08X}',
                          read_by_rules=readers, written_by_rules=writers,
                          associated_message_ids=posts))
    return dict(provenance='READ: SLES-026.88, 0x80016718 / 0x80017024 / 0x800EE4FC',
                binary_sha256=hashlib.sha256(binary).hexdigest(),
                archive_sha256=hashlib.sha256(archive).hexdigest(),
                schedule_archive_offset=schedule_off, code_archive_offset=code_off,
                slots=slots, rules=rules, messages=messages)


def csharp(data):
    lines = ['// Generated by tools/statistics.py from decoded FOLIO rules. Do not edit thresholds here.',
             'namespace TPW.Sim', '{',
             '    /// <summary>READ: all 125 rules, FOLIO entries 1/2; findings/statistics.md §4.',
             '    /// Action8 deliberately stays opaque: SOURCE DISAGREEMENTS §0 records the older',
             '    /// finding (game-state action) and the binary (remove a UI message).</summary>',
             '    public static class ParkStatisticRules', '    {',
             '        public static System.Collections.Generic.IReadOnlyList<StatisticRule> All { get; } =',
             '            System.Array.AsReadOnly(new StatisticRule[]', '            {']
    for r in data['rules']:
        ins = ', '.join('new(StatisticOpcode.' + i['op'] + ', ' +
                        ', '.join(str(a) for a in i['args']) + ')'
                        for i in r['instructions'])
        lines.append(f"                new({r['cooldown_days']}, new StatisticInstruction[] {{ {ins} }}), // rule {r['index']}, word {r['word_offset']}")
    lines += ['            });', '    }', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    data = decode(Path(sys.argv[1]).read_bytes(), Path(sys.argv[2]).read_bytes())
    (ROOT / 'findings/statistics-rules.json').write_text(json.dumps(data, indent=2) + '\n')
    (ROOT / 'core/TPW.Sim/ParkStatisticRules.cs').write_text(csharp(data))
    print(f"Decoded {len(data['slots'])} slots, {len(data['rules'])} rules, {len(data['messages'])} message labels.")
